# Generated by Django 4.2.4 on 2023-09-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('zapisano', 'Zapisano'), ('odwołano', 'Odwołano')], default='zapisano', max_length=10),
        ),
    ]
